# .github/workflows/chromatic.yml

name: "Build and publish to Chromatic"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        # ⚠️ Pick one of these, matching the package manager for your project
        run: pnpm install

      - name: Test
        run: pnpm test

      # - name: Publish to Chromatic
      #   uses: chromaui/action@latest
      #   with:
      #     # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
      #     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
