name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Write env file
        run: |
          echo "VITE_COINGECKO_API_URL=https://api.toshimoto.app/api/prices/range" >> apps/web-ui/.env.cy
          echo "VITE_COINGECKO_PRICE_API_URL=https://api.toshimoto.app/api/prices/simple" >> apps/web-ui/.env.cy
          echo "VITE_TOSHI_MOTO_XPUB=${{ secrets.VITE_TOSHI_MOTO_XPUB }}" >> apps/web-ui/.env.cy
          echo "VITE_BITCOIN_NETWORK=mainnet" >> apps/web-ui/.env.cy
          echo "VITE_REST_TIME_BETWEEN_REQUESTS=0" >> apps/web-ui/.env.cy
          echo "VITE_MAX_CONCURRENT_REQUESTS=8" >> apps/web-ui/.env.cy
          echo "CI=true" >> apps/web-ui/.env.cy
          echo "VITE_PRICING_API_URL=https://api.toshimoto.app" >> apps/web-ui/.env.cy
          echo "VITE_BITCOIN_NODE_URL=https://mempool.space" >> apps/web-ui/.env.cy

      - name: Lint
        run: npx nx affected --target=lint --base=origin/${{ github.event.pull_request.base.ref }} --head=$GITHUB_SHA

      - name: Tests
        run: npx nx affected --target=test --base=origin/${{ github.event.pull_request.base.ref }} --head=$GITHUB_SHA

      - name: Debug dir
        run: |
          cat apps/web-ui/.env.cy

      - name: Cypress Run
        id: cypress_run
        continue-on-error: true
        run: |
          npx nx run web-ui-e2e:e2e-ci

      - name: Check Cypress Result
        id: check_cypress
        run: |
          if [ "${{ steps.cypress_run.outcome }}" == "failure" ]; then
            echo "cypress_failed=true" >> $GITHUB_ENV
          else
            echo "cypress_failed=false" >> $GITHUB_ENV
          fi

      - name: Git status
        run: |
          git status
      - name: Check if files have changed in the specified directory
        id: file_check
        run: |
          if [[ -n $(git status --porcelain apps/web-ui-e2e/cypress/screenshots/) ]]; then
            echo "CHANGED=true" >> $GITHUB_ENV
          else
            echo "CHANGED=false" >> $GITHUB_ENV
          fi

      - name: grab the screenshots
        id: screenshot_status
        if: env.CHANGED == 'true'
        run: |
          echo "GIT_STATUS_OUTPUT<<EOF" >> $GITHUB_ENV
           git status --porcelain apps/web-ui-e2e/cypress/screenshots/ >> $GITHUB_ENV
           echo "EOF" >> $GITHUB_ENV

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Updating screenshots
        if: env.CHANGED == 'true'
        run: |
          git add apps/web-ui-e2e/cypress/screenshots
          git commit -m "chore(pipeline): update images"
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: GitHub Push
        if: env.CHANGED == 'true'
        uses: ad-m/github-push-action@v0.8.0
        with:
          branch: ${{ github.head_ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Construct Commit URL
        run: echo "COMMIT_URL=https://github.com/${GITHUB_REPOSITORY}/commit/${{ env.COMMIT_HASH }}" >> $GITHUB_ENV

      - name: Comment on PR
        run: node .github/scripts/comment-on-pr.mjs
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_BODY: "${{ env.COMMENT_BODY }}"
          COMMIT_URL: "${{ env.COMMIT_URL }}"
          GIT_STATUS_OUTPUT: "${{ env.GIT_STATUS_OUTPUT }}"
          BASE: "${{ github.event.pull_request.base.ref }}"
          HEAD: ${{ github.sha }}
          IMAGE_CHANGES: "${{ env.CHANGED }}"

      - name: Check if web-ui is affected
        id: check_affected
        run: |
          echo "Checking if web-ui is affected..."
          OUTPUT=$(npx nx show projects --affected --exclude web-ui-e2e --base=${{github.event.pull_request.base.ref}} --head=${{github.event.pull_request.head_ref}})
          echo "Affected apps: $OUTPUT"
          if [[ "$OUTPUT" == *"web-ui"* ]]; then
            echo "::set-output name=web_ui_affected::true"
          else
            echo "::set-output name=web_ui_affected::false"
          fi

      - name: Send bundle stats to RelativeCI
        uses: relative-ci/agent-action@v2
        if: steps.check_affected.outputs.web_ui_affected == 'true'
        with:
          webpackStatsFile: ./dist/apps/web-ui/webpack-stats.json
          key: ${{ secrets.RELATIVE_CI_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload Cypress Screenshots
      #   if: failure() # This ensures screenshots are uploaded only if the previous step fails
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: cypress-screenshots
      #     path: dist/cypress/apps/web-ui-e2e/screenshots/**/*
      #if-no-files-found: ignore # This option will prevent the step from failing if no screenshots are found

      # this may not be needed. the build is run when docker is built
      # - name: Build
      #   run: |
      #     npx nx affected --target=build --base=origin/${{ github.event.pull_request.base.ref }} --head=$GITHUB_SHA
      #
