name: PR Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  pull-request-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Determine the base commit of the PR
        id: determine_base
        run: echo "BASE=origin/main >> $GITHUB_ENV

      - name: Determine the head commit of the PR
        id: determine_head
        run: echo "HEAD=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: Lint
        run: npx nx affected --target=lint --base=$BASE --head=$HEAD

      - name: Test
        run: npx nx affected --target=test --base=$BASE --head=$HEAD

      - name: Build
        run: npx nx affected --target=build --base=$BASE --head=$HEAD

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Release
        run: npx nx affected --target=version --base=$BASE --head=$HEAD

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          tags: true
