name: PR Merge
# This runs twice on merge to main.
# once for versioning from merge
# once for pushing to relative ci
# dont think relative ci is configure properly
# i was expecting the merge alone would work
# but since it runs from the merged branch it
# doesnt sync with relative ci
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  pull-request-merge:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: production
    env:
      CI: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      # - name: Cache pnpm dependencies
      #   id: pnpm-cache
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.pnpm-store
      #       node_modules
      #       ~/.cache
      #     key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Determine the base commit of the PR
        id: determine_base
        run: echo "BASE=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV

      - name: Determine the head commit of the PR
        id: determine_head
        run: echo "HEAD=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: Define BASE and HEAD
        run: |
          echo "BASE=${{ github.event.before }}" >> $GITHUB_ENV
          echo "HEAD=${{ github.event.after }}" >> $GITHUB_ENV
        if: github.event_name == 'push'

      # - name: Lint
      #   run: npx nx affected --target=lint --base=$BASE --head=$HEAD

      # dont think this is needed.
      - name: Write env file
        run: |
          echo "VITE_COINGECKO_API_URL=https://api.toshimoto.app/api/prices/range" >> apps/web-ui/.env.cy
          echo "VITE_COINGECKO_PRICE_API_URL=https://api.toshimoto.app/api/prices/simple" >> apps/web-ui/.env.cy
          echo "VITE_TOSHI_MOTO_XPUB=${{ secrets.VITE_TOSHI_MOTO_XPUB }}" >> apps/web-ui/.env.cy
          echo "VITE_BITCOIN_NETWORK=mainnet" >> apps/web-ui/.env.cy
          echo "VITE_REST_TIME_BETWEEN_REQUESTS=0" >> apps/web-ui/.env.cy
          echo "VITE_MAX_CONCURRENT_REQUESTS=8" >> apps/web-ui/.env.cy
          echo "CI=true" >> apps/web-ui/.env.cy
          echo "VITE_PRICING_API_URL=https://api.toshimoto.app" >> apps/web-ui/.env.cy
          echo "VITE_BITCOIN_NODE_URL=https://mempool.space" >> apps/web-ui/.env.cy
          echo "VITE_IS_UMBREL=false" >> apps/web-ui/.env.cy
          echo "VITE_API_URL=https://api.toshimoto.app" >> apps/web-ui/.env.cy
          echo "VITE_PRICING_STREAM_DISABLED=1" >> apps/web-ui/.env.cy
      - name: Test
        run: npx nx affected --target=test --base=$BASE --head=$HEAD

      - name: Build
        run: npx nx affected --target=build --base=$BASE --head=$HEAD

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get Changelog Files
        id: ls_screenshots
        # | head -n 1 only gets the first line of the output
        run: |
          OUTPUT=$(npx nx run web-ui-e2e:ls | grep 'web-ui-e2e --')
          echo "$OUTPUT"
          echo "nx_output=$OUTPUT" >> $GITHUB_OUTPUT

      - name: Echo output
        run: |
          echo "${{ steps.ls_screenshots.outputs.nx_output }}"

      - name: Release
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: npx nx affected --target=version --exclude='*,!tag:deployable' --base=$BASE --head=$HEAD
        env:
          SHA: ${{ env.HEAD }}
          FILES: ${{ steps.ls_screenshots.outputs.nx_output }}

      - name: GitHub Push
        if: github.event_name == 'pull_request'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          tags: true

      - name: Check if web-ui is affected
        id: check_affected
        run: |
          echo "Checking if web-ui is affected..."
          OUTPUT=$(npx nx show projects --affected --exclude web-ui-e2e --base=$BASE --head=$HEAD)
          echo "Affected apps: $OUTPUT"
          if [[ "$OUTPUT" == *"web-ui"* ]]; then
            echo "::set-output name=web_ui_affected::true"
          else
            echo "::set-output name=web_ui_affected::false"
          fi

      - name: Send bundle stats to RelativeCI
        uses: relative-ci/agent-action@v2
        if: steps.check_affected.outputs.web_ui_affected == 'true'
        with:
          webpackStatsFile: ./dist/apps/web-ui/webpack-stats.json
          key: ${{ secrets.RELATIVE_CI_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
