name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: List Files (Debug)
        run: ls -R .github/workflows

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: npx nx affected --target=lint --base=origin/${{ github.event.pull_request.base.ref }} --head=$GITHUB_SHA

      - name: Tests
        run: npx nx affected --target=test --base=origin/${{ github.event.pull_request.base.ref }} --head=$GITHUB_SHA

      - name: Call cypress workflow
        uses: .github/workflows/cypress_screenshots.yml
        with:
          branch: ${{ github.head_ref }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload Cypress Screenshots
      #   if: failure() # This ensures screenshots are uploaded only if the previous step fails
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: cypress-screenshots
      #     path: dist/cypress/apps/web-ui-e2e/screenshots/**/*
      #if-no-files-found: ignore # This option will prevent the step from failing if no screenshots are found

      # this may not be needed. the build is run when docker is built
      # - name: Build
      #   run: |
      #     npx nx affected --target=build --base=origin/${{ github.event.pull_request.base.ref }} --head=$GITHUB_SHA
      #
