name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: npx nx affected --target=lint --base=origin/${{ github.event.pull_request.base.ref }} --head=$GITHUB_SHA

      - name: Tests
        run: npx nx affected --target=test --base=origin/${{ github.event.pull_request.base.ref }} --head=$GITHUB_SHA

      - name: Cypress Run
        id: cypress_run
        env:
          CYPRESS_RUNNING: true
          VITE_COINGECKO_API_URL: https://api.toshimoto.app/api/prices/range
          VITE_COINGECKO_PRICE_API_URL: https://api.toshimoto.app/api/prices/simple
          VITE_TOSHI_MOTO_XPUB: ${{ secrets.VITE_TOSHI_MOTO_XPUB }}
          VITE_BITCOIN_NETWORK: mainnet
          VITE_REST_TIME_BETWEEN_REQUESTS: 0
          VITE_MAX_CONCURRENT_REQUESTS: 8
        continue-on-error: true
        run: |
          npx nx run web-ui-e2e:e2e-ci

      - name: Check Cypress Result
        id: check_cypress
        run: |
          if [ "${{ steps.cypress_run.outcome }}" == "failure" ]; then
            echo "cypress_failed=true" >> $GITHUB_ENV
          else
            echo "cypress_failed=false" >> $GITHUB_ENV
          fi

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Updating screenshots
        run: |
          git add .
          git commit -m "chore(pipeline): update images"
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          branch: ${{ github.head_ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Construct Commit URL
        run: echo "COMMIT_URL=https://github.com/${GITHUB_REPOSITORY}/commit/${{ env.COMMIT_HASH }}" >> $GITHUB_ENV

      - name: Comment on PR
        uses: ./.github/scripts/comment-on-pr
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_BODY: "Images updated. Cypress Status: ${{ env.cypress_failed }} [Check them out](${{ env.COMMIT_URL }})!"

      # - name: Upload Cypress Screenshots
      #   if: failure() # This ensures screenshots are uploaded only if the previous step fails
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: cypress-screenshots
      #     path: dist/cypress/apps/web-ui-e2e/screenshots/**/*
      #if-no-files-found: ignore # This option will prevent the step from failing if no screenshots are found

      # this may not be needed. the build is run when docker is built
      # - name: Build
      #   run: |
      #     npx nx affected --target=build --base=origin/${{ github.event.pull_request.base.ref }} --head=$GITHUB_SHA
      #
