name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && (contains(github.event.pull_request.labels.*.name, 'major') || contains(github.event.pull_request.labels.*.name, 'minor') || contains(github.event.pull_request.labels.*.name, 'patch'))

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Bump version
        run: |
          cd apps/web-ui
          if echo "$LABELS" | grep -q "major"
          then
            pnpm version major -m "Bump version to %s"
          elif echo "$LABELS" | grep -q "minor"
          then
            pnpm version minor -m "Bump version to %s"
          else
            pnpm version patch -m "Bump version to %s"
          fi
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
