name: test

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Docker

    permissions:
      contents: write # Ensure the token has write permissions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth setup-git

      - name: Trigger workflow in another repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run create-release-pr.yml --repo toshimoto821/toshimoto-app-store
