name: test

on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    environment: Docker

    permissions:
      contents: write # Ensure the token has write permissions

    steps:
      - name: Trigger workflow in another repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/toshimoto821/toshimoto-app-store/dispatches \
            -d '{"event_type":"custom_event"}'
