name: test

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Docker

    permissions:
      contents: write # Ensure the token has write permissions

    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: echo $GH_PAT | gh auth login --with-token

      - name: Trigger workflow in another repo
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: gh workflow run create-release-pr.yml --repo toshimoto821/toshimoto-app-store --ref master
